# Generated by Django 5.2.13 on 2026-06-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
