# Generated by Django 5.2.13 on 2026-07-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurant_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
