# Generated by Django 5.2.13 on 2026-04-18 18:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10 digit Indian mobile number', regex='^[6-9]\\d{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('visit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.CharField(max_length=10)),
                ('party_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('queue_type', models.CharField(choices=[('small', '1-2'), ('medium', '3-4'), ('large', '5+')], max_length=10)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('vip', 'VIP')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('seated', 'Seated'), ('completed', 'Completed'), ('no_show', 'No Show'), ('left', 'Left Queue')], default='waiting', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_wait_mins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('special_request', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='queue_manager.customer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='TableAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='queue_manager.queueentry')),
                ('table_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='restaurants.tableunit')),
            ],
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['restaurant', 'status'], name='queue_manag_restaur_6ae8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['restaurant', 'queue_type', 'status'], name='queue_manag_restaur_b1a4af_idx'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(fields=('restaurant', 'token_number'), name='unique_token_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='tableassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('queue_entry',), name='one_active_table_per_queue_entry'),
        ),
    ]
