# Generated by Django 5.2.13 on 2026-04-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tableassignment',
            name='one_active_table_per_queue_entry',
        ),
    ]
