# Generated by Django 5.2.13 on 2026-04-20 15:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queue_manager', '0002_remove_tableassignment_one_active_table_per_queue_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('wait_satisfaction', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('food_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('service_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('would_recommend', models.BooleanField(null=True)),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('queue_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='queue_manager.queueentry')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('queue_joined', 'Joined Queue'), ('two_ahead', 'Two Ahead'), ('you_are_next', 'You Are Next'), ('table_ready', 'Table Ready'), ('no_show_warn', 'No Show Warning'), ('feedback', 'Feedback Request'), ('delay_update', 'Delay Update')], max_length=30)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='sms', max_length=10)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('twilio_sid', models.CharField(blank=True, max_length=64)),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='queue_manager.queueentry')),
            ],
        ),
    ]
